const addModels = [{
  userId: undefined,
  name: "Cider Chalet-F: 2BRK 山景公寓",
  city: "馬納利",
  country: "印度",
  description:
    "Ménage - Beas 河畔的小屋，位於馬納利附近的殖民風格山區別墅，這處迷人的度假屋結合了山區與河岸景觀，提供專屬隱私空間。它擁有一個蘋果園，3 間舒適的臥室、一個帶壁爐的寬敞客廳、以及可曬日光的閣樓，視野直達河流與山脈，是朋友或家人悠閒度假的理想之地。\n\n附加資訊：\n-入住時間為下午1點，退房時間為上午10點。根據空房情況並提前告知，可提前入住或延遲退房。\n*若有空房，提前入住時間可為上午10點後。如需在上午10點前入住，將收取提前入住費用。\n*延遲退房需根據空房情況，可能需支付費用。請聯絡房東了解具體情況。",
  type: "公寓",
  adultCount: 4,
  childCount: 0,
  facilities: ["入口", "WiFi", "收音機", "電視"],
  pricePerNight: 2840,
  starRating: undefined, 
  imageUrls: [
    // "https://res.cloudinary.com/rahul4019/image/upload/v1694365883/Airbnb/Places/liz5ro0ahknewjsdjgsb.jpg",
    // "https://res.cloudinary.com/rahul4019/image/upload/v1694365796/Airbnb/Places/j2nyjfrkfocnmypobxyy.jpg",
    // "https://res.cloudinary.com/rahul4019/image/upload/v1694365907/Airbnb/Places/meewrjm30dxwi2bjhsgj.jpg",
    // "https://res.cloudinary.com/rahul4019/image/upload/v1694365919/Airbnb/Places/bnzwau9h3wllv7bckjxr.jpg",
    // "https://res.cloudinary.com/rahul4019/image/upload/v1694365935/Airbnb/Places/maaqd97vn8gntdhxqgwm.jpg",
  ],
  lastUpdated: undefined,
  bookings: [],
  checkIn: 13,
  checkOut: 10,
}];
